# Generated by Django 3.1.14 on 2025-03-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20250314_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='show_pokemon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
